from sentimental_analysis_api.exceptions.exceptions import ClassificationException